Address testthat deprecation warnings + drop mockery
r-lib/covr pull request #589
Opened 2024-12-12 20:33 UTC by olivroy

Fix #595

* Replace mockery with testthat new mocking approach
* Replace deprecated `testthat::with_mock()` with `testthat::with_mocked bindings()`. (Addresses warnings logged in https://github.com/r-lib/covr/actions/runs/12316159627/job/34375845219#step:6:185)

They turned more challenging to fix than I expected.

I therefore removed the mockery dependency and `testthat::with_mock()` usage, but that required a bit of refactoring, such as importing from `{httr}` namespace to be able to mock `httr::content`, `httr::RETRY`, etc.

Kept everything related to mocking here to address testthat 3.2.2 deprecation warnings and sent other things to other PRs.

2024-12-12 21:07 UTC, jimhester commented
Hi, thanks for working on the changes, but before you go further could you provide some motivation for the changes. Particularly if they are going to touch a lot of files and be largely cosmetic vs functional.

2024-12-12 21:21 UTC, olivroy reviewed
Here are some explanations of what I did.

I decided to run styler on test-codecov.R and test-coveralls.R, because the indentation was quite inconsistent and we have an automated way to do it. It produces a more difficult to read diff, but at least the code style is consistent.

Happy to split if it makes it easier

2024-12-12 21:21 UTC, olivroy commented on NAMESPACE
> +importFrom(httr,upload_file)
Required to use testthat mocking https://testthat.r-lib.org/reference/local_mocked_bindings.html?q=local_mock#namespaced-calls

2024-12-12 21:21 UTC, olivroy commented on R/compiled.R
>      return(NULL)
These changes are required to remove the mockery dependency. I kept the commit self-contained.

But basically, with `mockery::stub()`, we can mock a function contained to a function. For example, mocking `file.exists()` only inside `parse_gcov()`. However, `testthat::local_mocked_bindings()` doesn't provide this ability.

The workaround I found is to create a wrapper function for `file.exists()` (in this case `source_file_exists()`.) that I will only use inside `parse_gcov()`. This way, I can mock `source_file_exists()` to only mock `file.exists()` inside `parse_gcov()`.

2024-12-12 21:21 UTC, olivroy commented on R/summary_functions.R
This was the original intent of my PR. Import cli instead of crayon. See the visual change in the PR main comment

2024-12-12 21:21 UTC, olivroy commented on R/summary_functions.R
> +#' @export
Fix warnings flagged by roxygen2 7.3.0 about the need to add an `@export` tag to un-exported S3 methods

2024-12-12 21:21 UTC, olivroy commented on tests/testthat/test-S7.R
> +  skip_if_not_installed("S7")
We already use 3rd edition of testthat. However, I ran into a mysterious error, before I realized I needed S7 installed to run the test successfully.

We get the following error if S7 is not installed

```r
cov <- as.data.frame(package_coverage(test_path("TestS7")))
Erreur dans file(con, "r") : impossible d'ouvrir la connexion
De plus : Message d'avis :
Dans file(con, "r") :
  impossible d'ouvrir le fichier 'C:/Users/user/AppData/Local/Temp/Rtmpa6QeqF/R_LIBSabf41a0d52a3/TestS7/R/TestS7' : No such file or directory
Appels : as.data.frame -> package_coverage -> add_hooks -> readLines -> file
````

2024-12-12 21:21 UTC, olivroy commented on tests/testthat/test-coveralls.R
> +cov <- package_coverage(test_path("TestS4"))
Easier to run tests interactively.

2024-12-12 21:21 UTC, olivroy commented on tests/testthat/test-coveralls.R
>  })
An example of replacing `with_mock()` with `with_mocked_bindings()`.

In short, we cannot have namespaced functions. And we give it a series of functions to mock. And then provide which code to run with the mocking. Very similar to `withr::with_*()` syntax.

2024-12-12 21:21 UTC, olivroy commented on tests/testthat/test-print.R
> -  cov <- package_coverage("TestPrint")
Could remove this and have it as the same test as previous, since they rely on the same package coverage. Allows to compute coverage only once.

2024-12-12 21:21 UTC, olivroy commented on tests/testthat/test-utils.R
> -
Leftover testthat deprecation warning!

2024-12-13 13:35 UTC, olivroy commented on tests/testthat/test-gcov.R
> -  expect_equal(parse_gcov("hi.c.gcov"), numeric())
Inside `parse_gcov()`, I replaced `readLines()` by `read_lines_impl()` to be able to mock `readLines()` only inside `parse_gcov()`

2025-01-09 13:16 UTC, olivroy commented
@jimhester Let me know if you need more explanation for this PR

from testthat changelog explaining the removal of `with_mock()`

> with_mock() and local_mock() have been unconditionally deprecated as they will no longer work in future versions of R (r-lib/testthat#1999).

More on transition to new functions from mockery https://www.tidyverse.org/blog/2023/10/testthat-3-2-0/#mocking

2025-01-13 17:02 UTC, jimhester requested changes
I made a few comments on how the mocking was setup, but overall looks good.

Can you please also add a bullet to NEWS? It should briefly [describe the change](https://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

2025-01-28 16:17 UTC, jimhester approved these changes

2025-01-28 16:17 UTC, jimhester commented
Thanks again for working on this, the changes look good!

2025-01-28 16:17 UTC, merged

2025-01-28 22:15 UTC, hadley commented on tests/testthat/test-coveralls.R
> +    with_mocked_bindings(
@olivroy if you have a bit more time, I think it would be worth switching these to use to `local_envvar()` and `local_mocked_bindings()` to reduce some of the nesting.